In [ ]:
import os
thisdir=os.getcwd()
#print(os.listdir("../.."))
#print(os.path.exists(".."))
i=0

for (dirpath,dirnames,filenames) in os.walk(thisdir):
    print(i)
    print(dirpath)
    print(dirnames)
    print(filenames)
    i+=1


In [16]:
a={'b':1,'c':2}
len(a)

2

In [15]:
a='a'
b='b'
alist=[a]
alist.append(['cde'])
print(alist)

['a', ['cde']]


In [5]:
round(3.2)

3

In [10]:
a=1;b=3
print(a,'b %d' % a)

1 b 1


In [3]:
a=3
try:a
except:print('no')

In [4]:
any([])

False

In [7]:
'b' in ['a','b']

True

In [9]:
import numpy as np
np.mean([1,2,3])
np.ones((10,2)).T

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
import numpy as np
#np.linspace(-4,4,9)
#print(np.log(np.exp(1)))

b=np.arange(64).reshape([2,2,2,2,2,2])
print(b[:,:,:,0,0,0])
print(b[...,0,0,0])

[[[ 0  8]
  [16 24]]

 [[32 40]
  [48 56]]]
[[[ 0  8]
  [16 24]]

 [[32 40]
  [48 56]]]


In [13]:
count=34
gridrange=8
log_gridrange=np.log(gridrange)
log_grid=np.linspace(-log_gridrange,log_gridrange,count)
grid=np.concatenate((-np.exp(-log_grid[log_grid<0]),log_grid[log_grid==0],np.exp(log_grid[log_grid>0])),axis=0)
print(grid)

[-8.         -7.05273004 -6.21762513 -5.48140394 -4.83235778 -4.26016436
 -3.75572364 -3.31101312 -2.91896021 -2.5733298  -2.26862504 -2.
 -1.76318251 -1.55440628 -1.37035098 -1.20808944 -1.06504109  1.06504109
  1.20808944  1.37035098  1.55440628  1.76318251  2.          2.26862504
  2.5733298   2.91896021  3.31101312  3.75572364  4.26016436  4.83235778
  5.48140394  6.21762513  7.05273004  8.        ]


In [25]:
count=35
gridrange=8
log_gridrange=np.log(gridrange)
log_grid=np.linspace(-log_gridrange,log_gridrange,count//2)
if count%2==1: zerolist=np.array([0])
else:zerolist=np.array([])
halfgrid=np.exp(log_grid)
grid=np.concatenate((-halfgrid[::-1],zerolist,halfgrid),axis=0)
print(grid)
print(np.diff(grid))

[-8.         -6.1688433  -4.75682846 -3.66801617 -2.82842712 -2.18101547
 -1.68179283 -1.29683955 -1.         -0.77110541 -0.59460356 -0.45850202
 -0.35355339 -0.27262693 -0.2102241  -0.16210494 -0.125       0.
  0.125       0.16210494  0.2102241   0.27262693  0.35355339  0.45850202
  0.59460356  0.77110541  1.          1.29683955  1.68179283  2.18101547
  2.82842712  3.66801617  4.75682846  6.1688433   8.        ]
[1.8311567  1.41201484 1.08881229 0.83958905 0.64741166 0.49922263
 0.38495328 0.29683955 0.22889459 0.17650186 0.13610154 0.10494863
 0.08092646 0.06240283 0.04811916 0.03710494 0.125      0.125
 0.03710494 0.04811916 0.06240283 0.08092646 0.10494863 0.13610154
 0.17650186 0.22889459 0.29683955 0.38495328 0.49922263 0.64741166
 0.83958905 1.08881229 1.41201484 1.8311567 ]


In [43]:
count=44
gridrange=5
log_gridrange=np.log(gridrange+1)
log_grid=np.linspace(0,log_gridrange,(count+2)//2)
halfgrid=np.exp(log_grid[1:])-1
grid=np.concatenate((-halfgrid[::-1],np.array([0]),halfgrid),axis=0)
print(grid)
print(grid.shape)
print(np.diff(grid))

[-5.         -4.53070811 -4.09812204 -3.69937082 -3.33180806 -2.99299433
 -2.68068102 -2.3927954  -2.12742684 -1.88281417 -1.65733395 -1.44948974
 -1.25790213 -1.08129961 -0.91851011 -0.76845323 -0.63013311 -0.50263174
 -0.38510292 -0.27676666 -0.17690396 -0.08485204  0.          0.08485204
  0.17690396  0.27676666  0.38510292  0.50263174  0.63013311  0.76845323
  0.91851011  1.08129961  1.25790213  1.44948974  1.65733395  1.88281417
  2.12742684  2.3927954   2.68068102  2.99299433  3.33180806  3.69937082
  4.09812204  4.53070811  5.        ]
(45,)
[0.46929189 0.43258607 0.39875122 0.36756277 0.33881373 0.31231331
 0.28788562 0.26536856 0.24461267 0.22548022 0.20784421 0.19158761
 0.17660252 0.1627895  0.15005687 0.13832013 0.12750137 0.11752881
 0.10833626 0.09986271 0.09205191 0.08485204 0.08485204 0.09205191
 0.09986271 0.10833626 0.11752881 0.12750137 0.13832013 0.15005687
 0.1627895  0.17660252 0.19158761 0.20784421 0.22548022 0.24461267
 0.26536856 0.28788562 0.31231331 0.3388137

In [ ]:
a=[1,2,[[3,4],4]]
aa=[1,2,[[3,2],4]]
b=[4,5,6]
c=[a,b]
d=[b,a]
e=[c,d]
f=[ii for i in e for ii in i]
print(e)
print(f)
print(a==aa)
print(all([a[i]==aa[i] for i in range(len(a))]))

In [ ]:
all(a)==all(aa)

In [ ]:
a=()
b=a+(1,)
b

In [ ]:
dict==list


In [ ]:
import datetime
datetime.datetime.strptime(None,"%Y%m%d-%H%M%S")   
print('a'
     'b')

In [ ]:
from copy import deepcopy
a={'a':np.arange(2)}
b={'a':np.arange(3)}
c=all(a)==all(b)
print(c)

In [ ]:
import os
os.path.exists(os.getcwd())


In [ ]:
print(all([True,False]))

In [ ]:
from copy import deepcopy
c=[2,3]
adoubledict={'test_string':c}
string='test_string'
new_dict={string:adoubledict[string]}
print(new_dict)
a=deepcopy(new_dict)
b=new_dict.copy()
c.append(4)
print(new_dict)
print(a)
print(b)

In [ ]:
from time import strftime
now=strftime("%Y%m%d-%H%M%S")
print(now)

In [ ]:
import os
#os.listdir()
b=None
#os.listdir(None)
os.chdir(os.path.join('c:/users/','dpatton','documents'))
os.listdir(None)

In [ ]:
import os
os.chdir('o:/public/dpatton/')
os.getcwd()

In [ ]:
a=([],1)
a[0].append(2)
a

In [ ]:
a=[1]
a.append(a.append(2))
print(a)

In [6]:
b={'a':[1,2]}
b['a'].append(3)
print(b)
b.items()[0]

{'a': [1, 2, 3]}


TypeError: 'dict_items' object is not subscriptable

In [ ]:
import numpy as np
np.round(np.log(1001),0)
np.abs(-1)

In [ ]:
a=None
def printor(b):
    if b==None or b.lower()=='yes':
        print('boom')
printor(None)
printor('Yes')

In [ ]:
[0]*2

In [ ]:
a=[1,2,3]
print(a[-99:])

In [ ]:
a=[1,2,3]
print(a)
b=a.copy()
b[0]=99
print(a)
a[True,True,False]

In [ ]:
a={'b':1,'c':2}
d=a.copy()
d['b']=None
print(a)

In [ ]:
import numpy as np
from time import strftime
timestr = strftime("%Y%m%d-%H%M%S")
print(timestr)
np.arange(10**9)
timestr = strftime("%Y%m%d-%H%M%S")
print(timestr)

In [ ]:
print(run1.optimizedict)
partial_newdict={'hyper_param_dict':{'Ndiff_exponent':'boom!'}}
altereddict=run1.do_dict_override(run1.optimizedict,partial_newdict)
print(altereddict)

In [ ]:
import numpy as np
a=[i for i in range(2,0,-1)]
print(str(a)+'test\n'+'test2')
b=[i+3 for i in a]
print(b)
amax=max(a)
print(a.index(amax))

In [ ]:
print(type('a'))

In [ ]:
import data_gen as dg
gen_params=2
data1=dg.data_gen(data_shape=(500,gen_params),seed=1,ftype='quadratic',evar=3)
#xdata=data1.x[:,:-1]#drop last x
size=65
xdata=data1.x[0:size,:gen_params+1]
ydata=data1.y[0:size]
y=ydata
xfull=xdata
x=xdata[:,1:] #drop first column of x (all 1's)
e=data1.e
n,p=x.shape
print(x.shape)
print(f'xdata.shape{xdata.shape}')

xvalidate=data1.x[100:500,1:]
yvalidate=data1.y[100:500]

In [ ]:
a=np.arange(64).reshape(4,4,4)
b=np.transpose(a,[1,0,2])
c=np.transpose(b,[1,0,2])
a-c

In [ ]:
a_tup=(1,2,3)
a_tup_list=list(a_tup)
print(a_tup_list)
a_tup_again=tuple(a_tup_list)
print(a_tup_again)

In [ ]:
b=[:]

In [ ]:
a=np.arange(64).reshape(4,4,4)
print(a)
b=(slice(None),[0,],slice(None))
print(a[b].shape)
c=(None,0,slice(None))
print(a[c].shape)

In [ ]:
Ndiff_start=2
this_depth_mask=np.arange(64).reshape(4,4,4)
mask_select=list((slice(None),)*this_depth_mask.ndim)
for dim in range(Ndiff_start-1,0,-1):
    mask_select[dim]=[0,]
mask_tup=tuple(mask_select)
this_depth_mask=this_depth_mask[mask_tup]
print(this_depth_mask.shape)

In [ ]:
import mykern as mk
a=np.linspace(1,10,10)
b=np.linspace(1,10,3)
tooltest=mk.kNdtool()
c=tooltest.makediffmat_itoj(a,b)
print(c)

In [ ]:
a=tooltest.MY_KDE_gridprep_smalln(40,6)
a.shape

In [ ]:
a=np.linspace(1,4,4)
aa=np.meshgrid(a,100*a)

b=np.concatenate(aa)
print(b.shape)
b.reshape()

In [ ]:
a=np.tile(np.arange(4)[:,None],[4,1])
b=np.repeat(np.arange(16).reshape(4,4),4,axis=0)
c=np.concatenate((a,b),axis=1)
print(c)

In [1]:
a=(3,2)
b=a+(1,)
b

(3, 2, 1)

In [2]:
b.sum()

AttributeError: 'tuple' object has no attribute 'sum'

In [3]:
a=[1,2,3]
a.sum()

AttributeError: 'list' object has no attribute 'sum'

In [4]:
sum(a)

6

In [5]:
b=[a,1]
sum(b)

TypeError: unsupported operand type(s) for +: 'int' and 'list'