In [2]:
import numpy as np
a=[i for i in range(2,0,-1)]
print(a)
b=[i for i in range(2)]
print(b)

[2, 1]
[0, 1]


In [3]:
import data_gen as dg
gen_params=2
data1=dg.data_gen(data_shape=(500,gen_params),seed=1,ftype='quadratic',evar=3)
#xdata=data1.x[:,:-1]#drop last x
size=65
xdata=data1.x[0:size,:gen_params+1]
ydata=data1.y[0:size]
y=ydata
xfull=xdata
x=xdata[:,1:] #drop first column of x (all 1's)
e=data1.e
n,p=x.shape
print(x.shape)
print(f'xdata.shape{xdata.shape}')

xvalidate=data1.x[100:500,1:]
yvalidate=data1.y[100:500]

self.x.shape(500, 5)
(65, 2)
xdata.shape(65, 3)


In [39]:
a=np.arange(64).reshape(4,4,4)
b=np.transpose(a,[1,0,2])
c=np.transpose(b,[1,0,2])
a-c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [10]:
a_tup=(1,2,3)
a_tup_list=list(a_tup)
print(a_tup_list)
a_tup_again=tuple(a_tup_list)
print(a_tup_again)

[1, 2, 3]
(1, 2, 3)


In [15]:
b=[:]

SyntaxError: invalid syntax (<ipython-input-15-c2d2672d5279>, line 1)

In [31]:
a=np.arange(64).reshape(4,4,4)
print(a)
b=(slice(None),[0,],slice(None))
print(a[b].shape)
c=(None,0,slice(None))
print(a[c].shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]
(4, 1, 4)
(1, 4, 4)


In [36]:
Ndiff_start=2
this_depth_mask=np.arange(64).reshape(4,4,4)
mask_select=list((slice(None),)*this_depth_mask.ndim)
for dim in range(Ndiff_start-1,0,-1):
    mask_select[dim]=[0,]
mask_tup=tuple(mask_select)
this_depth_mask=this_depth_mask[mask_tup]
print(this_depth_mask.shape)

(4, 1, 4)


In [2]:
import mykern as mk
a=np.linspace(1,10,10)
b=np.linspace(1,10,3)
tooltest=mk.kNdtool()
c=tooltest.makediffmat_itoj(a,b)
print(c)

[[ 0.  -4.5 -9. ]
 [ 1.  -3.5 -8. ]
 [ 2.  -2.5 -7. ]
 [ 3.  -1.5 -6. ]
 [ 4.  -0.5 -5. ]
 [ 5.   0.5 -4. ]
 [ 6.   1.5 -3. ]
 [ 7.   2.5 -2. ]
 [ 8.   3.5 -1. ]
 [ 9.   4.5  0. ]]


In [8]:
a=tooltest.MY_KDE_gridprep_smalln(40,6)
a.shape

MemoryError: 

In [4]:
a=np.linspace(1,4,4)
aa=np.meshgrid(a,100*a)

b=np.concatenate(aa)
print(b.shape)
b.reshape()

(8, 4)


TypeError: reshape() takes exactly 1 argument (0 given)

In [ ]:
a=np.tile(np.arange(4)[:,None],[4,1])
b=np.repeat(np.arange(16).reshape(4,4),4,axis=0)
c=np.concatenate((a,b),axis=1)
print(c)

In [3]:
a=(3,2)
b=a+(1,)
b

(3, 2, 1)